spring.application.name=finanzas
server.port=${PORT_USER:8080}

# ===================================================================
# CONFIGURACIÓN DE POSTGREYSQL (pgAdmin 4)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:salud_financiera}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate y JPA para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURACIÓN DE MICROSERVICIO PYTHON
# ===================================================================
python.nlp.service.url=http://localhost:8000

# ==========================================
# ? CONFIGURACIÓN DE SWAGGER / OPENAPI 3
# ==========================================

# Ruta para acceder a la interfaz gráfica de Swagger UI (Ej: http://localhost:8008/swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html

# Ordenar alfabéticamente los endpoints (HTTP methods / Paths)
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

# Deshabilitar / Habilitar la prueba de endpoints ("Try it out") en Swagger UI (true por defecto)
springdoc.swagger-ui.tryItOutEnabled=true

# Ruta personalizada para exponer la especificación en JSON de OpenAPI (Ej: http://localhost:8008/v3/api-docs)
springdoc.api-docs.path=/v3/api-docs

# Permite habilitar/deshabilitar Swagger dinámicamente (por defecto: true)
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}

# Mostrar la sección de esquemas DTO al final de la página por defecto
springdoc.swagger-ui.defaultModelsExpandDepth=1
springdoc.swagger-ui.defaultModelExpandDepth=1