services:
  financeai-db:
    image: postgres:16-alpine
    container_name: financeai_postgres_db
    environment:
      POSTGRES_DB: salud_financiera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d salud_financiera" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  financeai-python:
    build:
      context: ../HackatonG9-LATAM-Team17-feature-back-python-prueba
    container_name: financeai_python_api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - app-network

  financeai-backend:
    build:
      context: ./backend
    container_name: financeai_spring_backend
    ports:
      - "8008:8008"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://financeai-db:5432/salud_financiera
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secretpassword
      PYTHON_NLP_SERVICE_URL: http://financeai-python:8000
    depends_on:
      financeai-db:
        condition: service_healthy
      financeai-python:
        condition: service_started
    networks:
      - app-network

  financeai-frontend:
    build:
      context: ../frontend-financeai
    container_name: financeai_frontend_app
    ports:
      - "8080:80"
    depends_on:
      - financeai-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge