spring.application.name=finazas
# ===================================================================
# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/salud_financiera
spring.datasource.username=postgres
spring.datasource.password=programacionsql

# Controlador oficial de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# ddl-auto=update: Spring Boot creará o actualizará las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las sentencias SQL reales
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect