spring.application.name=finanzas
server.port=8008
# ===================================================================
# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Controlador oficial de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# # mientras duren las pruebas
spring.jpa.hibernate.ddl-auto=create-drop

# Permite que Spring cargue data.sql en bases de datos relacionales
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Muestra en la consola las sentencias SQL reales
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#============================================
# URL del Microservicio Data / Python NLP
python.nlp.service.url=http://localhost:8000
#============================================