spring.application.name=finanzas
server.port=8080

# ===================================================================
# CONFIGURACIÓN DE POSTGREYSQL (pgAdmin 4)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/salud_financiera
spring.datasource.username=postgres
spring.datasource.password=************

# Hibernate y JPA para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURACIÓN DE MICROSERVICIO PYTHON
# ===================================================================
python.nlp.service.url=http://localhost:8000