spring.application.name=finanzas
server.port=8080

# ===================================================================
# CONFIGURACIÓN PARA PRUEBAS (BASE DE DATOS H2 EN MEMORIA RAM)
# ===================================================================
spring.datasource.url=jdbc:h2:mem:finanzasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate y JPA para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURACIÓN DE MICROSERVICIO PYTHON
# ===================================================================
python.nlp.service.url=http://localhost:8000